(define (make-account balance password)
  (let ((counter 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (call-the-cops)
      "Call the cops")
    (define (incorrect-password account)
      (set! counter (+ counter 1))
      (if (>= counter 7)
          (call-the-cops)
          "Inccorect password"))
    (define (dispatch p m)
      (if (eq? p password)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (lambda (amount) (error "Unknown request -- MAKE-ACCOUNT" m))))
          incorrect-password))
    dispatch))
