(define (ring? x)
  (define (in? item lst)
    (cond ((null? lst) #f)
          ((eq? item (car lst)) #t)
          (else (in? item (cdr lst)))))
  (define (iter y checked)
    (cond ((null? y) #f)
          ((in? y checked) #t)
          (else (iter (cdr y) (cons y checked)))))
  (iter x '()))
