(define (or-gate input-1 input-2 output)
  (let ((o1 (make-wire))
        (o2 (make-wire))
        (o3 (make-wire)))
    (inverter input-1 o1)
    (inverter input-2 o2)
    (and-gate o1 o2 o3)
    (inverter o3 output)
    'ok))
